default:
  target: dev
  outputs:
    dev:
    prod:
      type: bigquery
      method: service-account
      dataset: cycling_prod
      threads: 4
      keyfile: "../../.google/credentials/google_credentials.json"
      timeout_seconds: 300
      location: 
      priority: interactive
