version: 2

sources:
      - name: staging
        database: balmy-component-381417
        schema: cycling_data_all

        tables:
            - name: external_cycling_data_partitioned_clustered
  

models:
      - name:  stg_cycling

