version: 2

sources:
      - name: staging
        database:  #insert your project name here
        schema: cycling_data_all

        tables:
            - name: external_cycling_data_partitioned_clustered
  

models:
      - name:  stg_cycling

